apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validatelabel
webhooks:
  - name: bekci.yildizozan.com
    clientConfig:
      url: https://bekci-ofjqk4ohpq-ez.a.run.app
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE"]
        scope: Namespaced
    namespaceSelector:
      matchLabels:
        validation: enabled
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
